CREATE DATABASE PROJECTSQL;
USE PROJECTSQL;

CREATE TABLE SALES(SALE_ID INT PRIMARY KEY, PRODUCT_ID INT, QUANTITY_SOLD INT, SALE_DATE DATE, TOTAL_PRICE DECIMAL(10,2));
INSERT INTO SALES VALUES(1, 101, 5, '2024-01-01', 2500.00);
INSERT INTO SALES VALUES(2, 102, 3, '2024-01-02', 900.00);
INSERT INTO SALES VALUES(3, 103, 2, '2024-01-02', 60.00);
INSERT INTO SALES VALUES(4, 104, 4, '2024-01-03', 80.00);
INSERT INTO SALES VALUES(5, 105, 6, '2024-01-03', 90.00);

SELECT * FROM SALES;

CREATE TABLE PRODUCTS(PRODUCT_ID INT PRIMARY KEY, PRODUCT_NAME VARCHAR(100), CATEGORY VARCHAR(50), UNIT_PRICE DECIMAL(10,2));
INSERT INTO PRODUCTS VALUES(101, 'LAPTOP', 'ELECTRONICS', 500.00);
INSERT INTO PRODUCTS VALUES(102, 'SMARTPHONE', 'ELECTRONICS', 300.00);
INSERT INTO PRODUCTS VALUES(103, 'HEADPHONE', 'ELECTRONICS', 30.00);
INSERT INTO PRODUCTS VALUES(104, 'KEYBOARD', 'ELECTRONICS', 20.00);
INSERT INTO PRODUCTS VALUES(105, 'MOUSE', 'ELECTRONICS', 15.00);

SELECT * FROM PRODUCTS;



SELECT PRODUCT_NAME, CATEGORY, UNIT_PRICE FROM PRODUCTS WHERE PRODUCT_ID IN 
                                   (SELECT PRODUCT_ID FROM SALES GROUP BY PRODUCT_ID HAVING SUM(QUANTITY_SOLD) > 
                                   (SELECT AVG(TOTAL_SOLD) FROM 
                                   (SELECT SUM(QUANTITY_SOLD) AS TOTAL_SOLD FROM SALES GROUP BY PRODUCT_ID) AS PRODUCT_SALES));



ALTER TABLE SALES ADD CONSTRAINT FOREIGN_KEY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID);



CREATE VIEW TOP_PRODUCTS AS 
               SELECT P.PRODUCT_NAME FROM PRODUCTS P JOIN SALES S ON P.PRODUCT_ID = S.PRODUCT_ID 
													 GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME 
                                                     ORDER BY SUM(QUANTITY_SOLD) DESC LIMIT 3;
SELECT * FROM TOP_PRODUCTS;
